name: paper_zampieri_2023
channels:
  - defaults
  - conda-forge
dependencies:
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - anyio=3.7.1
  - aom=3.5.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-lru=2.0.2
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.10
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blosc=1.21.4
  - bokeh=3.2.0
  - boost-cpp=1.78.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.05.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=3.2.0
  - click=8.1.4
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.1.0
  - curl=8.1.2
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.7.0
  - dask-core=2023.7.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.7.0
  - double-conversion=3.2.0
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - expat=2.5.0
  - fenics-basix=0.6.0
  - fenics-dolfinx=0.6.0
  - fenics-ffcx=0.6.0
  - fenics-libbasix=0.6.0
  - fenics-libdolfinx=0.6.0
  - fenics-ufcx=0.6.0
  - fenics-ufl=2023.1.1
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - flit-core=3.9.0
  - fltk=1.3.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.40.0
  - freeimage=3.18.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.6.0
  - gettext=0.21.1
  - gflags=2.2.2
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.76.4
  - glib-tools=2.76.4
  - glog=0.6.0
  - gmp=6.2.1
  - gmsh=4.11.1
  - gnutls=3.7.8
  - gst-plugins-base=1.22.4
  - gstreamer=1.22.4
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - hypre=2.25.0
  - icu=70.1
  - idna=3.4
  - imath=3.1.6
  - importlib-metadata=6.8.0
  - importlib-resources=6.0.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.0
  - ipykernel=6.24.0
  - ipython=8.14.0
  - ipywidgets=8.0.7
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.3.0
  - jpeg=9e
  - json5=0.9.14
  - jsoncpp=1.9.5
  - jsonschema=4.18.0
  - jsonschema-specifications=2023.6.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.23.0
  - jupyterlab_widgets=3.0.8
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.3
  - libadios2=2.8.3
  - libaec=1.0.6
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.4
  - libgoogle-cloud=2.12.0
  - libgrpc=1.54.2
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.1
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libraw=0.21.1
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - locket=1.0.0
  - loguru=0.7.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - meshio=5.3.4
  - metis=5.1.0
  - mistune=3.0.0
  - mpfr=4.2.0
  - mpi=1.0
  - mpi4py=3.1.4
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - mumps-include=5.2.1
  - mumps-mpi=5.2.1
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.8.0
  - nbconvert-core=7.6.0
  - nbformat=5.9.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - netcdf4=1.6.3
  - nettle=3.8.1
  - nlohmann_json=3.11.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89
  - numpy=1.25.1
  - occt=7.7.1
  - openexr=3.1.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openmpi=4.1.5
  - openssl=3.1.1
  - orc=1.9.0
  - overrides=7.3.1
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parmetis=4.0.3
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - petsc=3.17.4
  - petsc4py=3.17.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.8.1
  - pooch=1.7.0
  - proj=9.1.1
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptscotch=6.0.9
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - pyarrow=12.0.1
  - pybind11-abi=4
  - pycparser=2.21
  - pygments=2.15.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-gmsh=4.11.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - pyvista=0.40.0
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - rapidjson=1.1.0
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.29.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.4.2
  - rpds-py=0.8.8
  - scalapack=2.2.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - scooby=0.7.2
  - scotch=6.0.9
  - send2trash=1.8.2
  - setuptools=67.8.0
  - six=1.16.0
  - slepc=3.17.2
  - slepc4py=3.17.2
  - snappy=1.1.10
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.6.2
  - suitesparse=5.10.1
  - superlu=5.2.2
  - superlu_dist=7.2.0
  - svt-av1=1.4.1
  - tbb=2021.9.0
  - tbb-devel=2021.9.0
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - trame=2.5.0
  - trame-client=2.9.4
  - trame-components=2.1.1
  - trame-deckgl=2.0.2
  - trame-markdown=2.0.2
  - trame-matplotlib=2.0.2
  - trame-plotly=2.1.1
  - trame-rca=0.3.1
  - trame-router=2.0.2
  - trame-server=2.11.4
  - trame-simput=2.3.2
  - trame-vega=2.0.3
  - trame-vtk=2.5.4
  - trame-vuetify=2.2.4
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=2.0.3
  - utfcpp=3.2.3
  - vtk=9.2.6
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.38.4
  - widgetsnbextension=4.0.8
  - wslink=1.11.1
  - x264=1!164.3095
  - x265=3.5
  - xarray=2023.6.0
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2023.5.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=3.0.0
  - zipp=3.16.0
  - zlib=1.2.13
  - zstd=1.5.2
